### ISSUE TITLE
Wrong spelling in Dockerfile

### ISSUE THREAD

**Issue by technosight** [dbatten5/cookiecutter-fastapi-react-psql#48]
cookiecutter-fastapi-react-psql/{{cookiecutter.project_name}}/backend/Dockerfile:
    
1: ARG APP_DIRECTORY=/{{cookiecutter.prokect_slug}}

needs to be changed to:

1: ARG APP_DIRECTORY=/{{cookiecutter.project_slug}}

**Comment by dbatten5** [comment]
thanks for raising the issue @technosight, issue is resolved now
